import type {
  AutomationRule,
  BudgetChangeRequest,
  Client,
  Comment,
  FxRate,
  Invoice,
  Organization,
  Phase,
  Project,
  ProjectFile,
  Quote,
  QuoteLineItem,
  QuoteVersion,
  Task,
  TimeEntry,
  TimeTrackingConfig,
  TimesheetSubmission,
  User,
  UserSkill,
} from "@/types/domain";

export const ORG: Organization = {
  id: "org_atelier",
  slug: "atelier",
  name: "Atelier Studio",
  logoUrl: undefined,
};

export const USERS: User[] = [
  {
    id: "u_avery",
    fullName: "Avery Chen",
    email: "avery@atelier.studio",
    role: "super_admin",
    avatarUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=128&h=128&fit=crop",
  },
  {
    id: "u_marcus",
    fullName: "Marcus Wei",
    email: "marcus@atelier.studio",
    role: "pm",
    avatarUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=128&h=128&fit=crop",
  },
  {
    id: "u_lina",
    fullName: "Lina Okafor",
    email: "lina@atelier.studio",
    role: "member",
    avatarUrl:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=128&h=128&fit=crop",
  },
  {
    id: "u_nikolai",
    fullName: "Nikolai Petrov",
    email: "nik@atelier.studio",
    role: "member",
    avatarUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=128&h=128&fit=crop",
  },
  {
    id: "u_sade",
    fullName: "Sade Hassan",
    email: "sade@atelier.studio",
    role: "member",
    avatarUrl:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=128&h=128&fit=crop",
  },
  {
    id: "u_kai",
    fullName: "Kai Thompson",
    email: "kai@atelier.studio",
    role: "qa",
    avatarUrl:
      "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=128&h=128&fit=crop",
  },
];

export const CURRENT_USER_ID = "u_avery";

export const CLIENTS: Client[] = [
  {
    id: "c_lumiere",
    organizationId: ORG.id,
    code: "LUM-001",
    name: "Lumière Hotels",
    industry: "Hospitality",
    primaryContactName: "Isabelle Rousseau",
    primaryContactEmail: "isabelle@lumiere.com",
    currency: "USD",
    contractType: "retainer",
    status: "active",
    accountManagerId: "u_marcus",
    tags: ["VIP", "Luxury"],
    portalEnabled: true,
    createdAt: "2026-01-12T10:00:00Z",
  },
  {
    id: "c_orchid",
    organizationId: ORG.id,
    code: "ORC-001",
    name: "Orchid & Vine",
    industry: "Fashion",
    primaryContactName: "Theo Nakamura",
    primaryContactEmail: "theo@orchidvine.co",
    currency: "USD",
    contractType: "project",
    status: "active",
    accountManagerId: "u_avery",
    tags: ["E-commerce"],
    portalEnabled: true,
    createdAt: "2026-02-01T09:30:00Z",
  },
  {
    id: "c_haus",
    organizationId: ORG.id,
    code: "HAU-001",
    name: "Haus of Mode",
    industry: "Fashion",
    primaryContactName: "Petra Lindqvist",
    primaryContactEmail: "petra@hausofmode.com",
    currency: "EUR",
    contractType: "project",
    status: "active",
    accountManagerId: "u_avery",
    tags: ["Luxury", "Branding"],
    portalEnabled: false,
    createdAt: "2026-03-08T14:15:00Z",
  },
  {
    id: "c_meridian",
    organizationId: ORG.id,
    code: "MER-001",
    name: "Meridian Capital",
    industry: "Finance",
    primaryContactName: "Jordan Cole",
    primaryContactEmail: "jordan@meridian.cap",
    currency: "USD",
    contractType: "hybrid",
    status: "active",
    accountManagerId: "u_marcus",
    tags: ["Enterprise"],
    portalEnabled: true,
    createdAt: "2025-11-22T11:00:00Z",
  },
  {
    id: "c_terra",
    organizationId: ORG.id,
    code: "TER-001",
    name: "Terra Verde",
    industry: "Wellness",
    primaryContactName: "Mira Aulia",
    primaryContactEmail: "mira@terraverde.io",
    currency: "USD",
    contractType: "retainer",
    status: "on_hold",
    accountManagerId: "u_marcus",
    tags: ["Wellness"],
    portalEnabled: true,
    createdAt: "2025-09-14T08:45:00Z",
  },
];

export const PROJECTS: Project[] = [
  {
    id: "p_lumiere_site",
    organizationId: ORG.id,
    clientId: "c_lumiere",
    code: "LUM-001-WEB",
    name: "Lumière flagship website",
    type: "web_dev",
    startDate: "2026-03-01",
    endDate: "2026-06-15",
    status: "active",
    priority: "high",
    projectManagerId: "u_marcus",
    billingModel: "fixed_price",
    totalBudget: 185000,
    estimatedHours: 1240,
    description:
      "Reimagine Lumière's flagship hotel chain website with an editorial-grade booking experience and bilingual EN/FR support.",
    health: "green",
    tags: ["Web", "Booking", "Bilingual"],
    progress: 0.62,
    taskCounts: { total: 48, done: 30 },
    createdAt: "2026-02-20T10:00:00Z",
  },
  {
    id: "p_orchid_ecom",
    organizationId: ORG.id,
    clientId: "c_orchid",
    code: "ORC-001-WEB",
    name: "Orchid & Vine — Shopify replatform",
    type: "web_dev",
    startDate: "2026-02-15",
    endDate: "2026-05-30",
    status: "active",
    priority: "high",
    projectManagerId: "u_avery",
    billingModel: "milestone",
    totalBudget: 96000,
    estimatedHours: 720,
    description: "Replatform from BigCommerce to Shopify Plus with custom theme and headless cart.",
    health: "yellow",
    tags: ["E-commerce", "Shopify"],
    progress: 0.48,
    taskCounts: { total: 36, done: 17 },
    createdAt: "2026-02-10T13:00:00Z",
  },
  {
    id: "p_haus_brand",
    organizationId: ORG.id,
    clientId: "c_haus",
    code: "HAU-001-BRD",
    name: "Haus of Mode — Brand identity SS27",
    type: "branding",
    startDate: "2026-03-20",
    endDate: "2026-05-15",
    status: "active",
    priority: "medium",
    projectManagerId: "u_avery",
    billingModel: "fixed_price",
    totalBudget: 58000,
    estimatedHours: 380,
    description: "Brand identity refresh for SS27 collection. Logo system, type, color, motion, and guidelines.",
    health: "green",
    tags: ["Branding", "Identity"],
    progress: 0.34,
    taskCounts: { total: 22, done: 7 },
    createdAt: "2026-03-15T09:00:00Z",
  },
  {
    id: "p_meridian_app",
    organizationId: ORG.id,
    clientId: "c_meridian",
    code: "MER-001-APP",
    name: "Meridian client app — iOS & Android",
    type: "app_dev",
    startDate: "2026-01-10",
    endDate: "2026-08-20",
    status: "active",
    priority: "urgent",
    projectManagerId: "u_marcus",
    billingModel: "time_and_materials",
    totalBudget: 420000,
    estimatedHours: 2400,
    description: "Native iOS + Android client portfolio app with biometric auth and live market data.",
    health: "red",
    tags: ["Mobile", "FinTech"],
    progress: 0.41,
    taskCounts: { total: 84, done: 34 },
    createdAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "p_terra_seo",
    organizationId: ORG.id,
    clientId: "c_terra",
    code: "TER-001-SEO",
    name: "Terra Verde — SEO retainer Q2",
    type: "digital_marketing",
    startDate: "2026-04-01",
    endDate: "2026-06-30",
    status: "active",
    priority: "medium",
    projectManagerId: "u_marcus",
    billingModel: "retainer",
    totalBudget: 18000,
    estimatedHours: 120,
    description: "Q2 SEO retainer: technical audit, content calendar, monthly link building, performance reports.",
    health: "green",
    tags: ["SEO", "Retainer"],
    progress: 0.21,
    taskCounts: { total: 18, done: 4 },
    createdAt: "2026-03-25T11:00:00Z",
  },
];

const phaseTemplates: Record<string, string[]> = {
  web_dev: [
    "Discovery & Planning",
    "Information Architecture",
    "Wireframing",
    "UI Design",
    "Frontend Development",
    "Backend Development",
    "Content Integration",
    "QA & Testing",
    "Launch",
  ],
  app_dev: [
    "Discovery & Research",
    "UX Design",
    "UI Design",
    "Architecture & Setup",
    "Sprint Development",
    "QA & Testing",
    "Beta Testing",
    "Launch",
  ],
  digital_marketing: [
    "Audit & Research",
    "Strategy Development",
    "Content Creation",
    "Campaign Execution",
    "Reporting",
  ],
  branding: [
    "Discovery",
    "Research & Moodboarding",
    "Concept Development",
    "Logo Design",
    "Brand System",
    "Guidelines & Delivery",
  ],
  maintenance: ["Triage", "Implementation", "QA", "Release"],
  other: ["Planning", "Execution", "Review"],
};

export const PHASES: Phase[] = PROJECTS.flatMap((p) =>
  (phaseTemplates[p.type] ?? phaseTemplates.other).map((name, idx) => ({
    id: `${p.id}_phase_${idx + 1}`,
    projectId: p.id,
    name,
    position: idx + 1,
    isComplete: idx + 1 < (phaseTemplates[p.type]?.length ?? 5) * p.progress,
  })),
);

const taskSeeds: Array<
  Omit<
    Task,
    "id" | "code" | "organizationId" | "createdAt" | "updatedAt" | "subtasks"
  > & {
    projectId: string;
  }
> = [
  // Lumière flagship
  {
    projectId: "p_lumiere_site",
    phaseId: "p_lumiere_site_phase_1",
    title: "Stakeholder discovery workshops",
    description: "Run two half-day discovery workshops with marketing, ops, and revenue leads.",
    status: "done",
    priority: "high",
    taskType: "Research",
    dueDate: "2026-03-08",
    estimatedHours: 16,
    actualHours: 18,
    assigneeIds: ["u_marcus", "u_avery"],
    clientVisible: true,
    position: 1,
    tags: ["Discovery"],
    commentCount: 5,
    attachmentCount: 3,
    subtaskCount: 4,
    subtasksDone: 4,
  },
  {
    projectId: "p_lumiere_site",
    phaseId: "p_lumiere_site_phase_4",
    title: "Editorial homepage hero — concept A",
    description: "Cinematic hero with autoplay reel, subtle parallax, and bilingual headline animation.",
    status: "in_review",
    priority: "high",
    taskType: "Design",
    dueDate: "2026-04-30",
    estimatedHours: 12,
    actualHours: 9.5,
    assigneeIds: ["u_lina"],
    reviewerId: "u_avery",
    clientVisible: true,
    position: 2,
    tags: ["Hero", "Homepage"],
    figmaUrl: "https://figma.com/file/example",
    commentCount: 8,
    attachmentCount: 2,
    subtaskCount: 3,
    subtasksDone: 2,
  },
  {
    projectId: "p_lumiere_site",
    phaseId: "p_lumiere_site_phase_4",
    title: "Property detail page — gallery + amenities",
    status: "in_progress",
    priority: "medium",
    taskType: "Design",
    dueDate: "2026-05-08",
    estimatedHours: 18,
    actualHours: 6,
    assigneeIds: ["u_lina", "u_sade"],
    clientVisible: true,
    position: 3,
    tags: ["Property"],
    commentCount: 2,
    attachmentCount: 1,
    subtaskCount: 5,
    subtasksDone: 1,
  },
  {
    projectId: "p_lumiere_site",
    phaseId: "p_lumiere_site_phase_5",
    title: "Build booking flow — date picker + room selector",
    status: "in_progress",
    priority: "urgent",
    taskType: "Feature",
    dueDate: "2026-05-15",
    estimatedHours: 32,
    actualHours: 12,
    assigneeIds: ["u_nikolai"],
    reviewerId: "u_marcus",
    clientVisible: false,
    position: 4,
    tags: ["Booking", "Frontend"],
    repoUrl: "https://github.com/atelier/lumiere/pull/142",
    commentCount: 4,
    attachmentCount: 0,
    subtaskCount: 7,
    subtasksDone: 3,
  },
  {
    projectId: "p_lumiere_site",
    phaseId: "p_lumiere_site_phase_6",
    title: "Integrate booking engine API (Synxis)",
    status: "todo",
    priority: "high",
    taskType: "Feature",
    dueDate: "2026-05-22",
    estimatedHours: 24,
    actualHours: 0,
    assigneeIds: ["u_nikolai"],
    clientVisible: false,
    position: 5,
    tags: ["Backend", "Integration"],
    commentCount: 1,
    attachmentCount: 0,
    subtaskCount: 4,
    subtasksDone: 0,
  },
  {
    projectId: "p_lumiere_site",
    phaseId: "p_lumiere_site_phase_4",
    title: "Newsletter signup — design refinements",
    status: "revisions",
    priority: "low",
    taskType: "Design",
    dueDate: "2026-04-28",
    estimatedHours: 4,
    actualHours: 5.5,
    assigneeIds: ["u_sade"],
    reviewerId: "u_avery",
    clientVisible: true,
    position: 6,
    tags: ["Newsletter"],
    commentCount: 6,
    attachmentCount: 1,
    subtaskCount: 0,
    subtasksDone: 0,
  },
  {
    projectId: "p_lumiere_site",
    phaseId: "p_lumiere_site_phase_8",
    title: "Cross-browser QA — Safari iOS 17",
    status: "blocked",
    priority: "medium",
    taskType: "QA",
    dueDate: "2026-05-30",
    estimatedHours: 6,
    actualHours: 0,
    assigneeIds: ["u_kai"],
    clientVisible: false,
    position: 7,
    tags: ["QA"],
    commentCount: 3,
    attachmentCount: 0,
    subtaskCount: 0,
    subtasksDone: 0,
  },
  // Orchid & Vine
  {
    projectId: "p_orchid_ecom",
    phaseId: "p_orchid_ecom_phase_4",
    title: "PDP — variant picker animation",
    status: "in_progress",
    priority: "high",
    taskType: "Feature",
    dueDate: "2026-05-02",
    estimatedHours: 14,
    actualHours: 6,
    assigneeIds: ["u_lina"],
    clientVisible: true,
    position: 1,
    tags: ["PDP"],
    commentCount: 3,
    attachmentCount: 2,
    subtaskCount: 3,
    subtasksDone: 1,
  },
  {
    projectId: "p_orchid_ecom",
    phaseId: "p_orchid_ecom_phase_5",
    title: "Headless cart — checkout API",
    status: "in_review",
    priority: "urgent",
    taskType: "Feature",
    dueDate: "2026-05-09",
    estimatedHours: 28,
    actualHours: 22,
    assigneeIds: ["u_nikolai"],
    reviewerId: "u_marcus",
    clientVisible: false,
    position: 2,
    tags: ["Cart", "Shopify"],
    repoUrl: "https://github.com/atelier/orchid/pull/87",
    commentCount: 9,
    attachmentCount: 0,
    subtaskCount: 6,
    subtasksDone: 5,
  },
  {
    projectId: "p_orchid_ecom",
    phaseId: "p_orchid_ecom_phase_3",
    title: "Brand-tone copy — homepage + collections",
    status: "todo",
    priority: "medium",
    taskType: "Content",
    dueDate: "2026-05-04",
    estimatedHours: 10,
    actualHours: 0,
    assigneeIds: ["u_sade"],
    clientVisible: true,
    position: 3,
    tags: ["Copywriting"],
    commentCount: 0,
    attachmentCount: 0,
    subtaskCount: 0,
    subtasksDone: 0,
  },
  {
    projectId: "p_orchid_ecom",
    phaseId: "p_orchid_ecom_phase_8",
    title: "Migration plan — orders + customers",
    status: "todo",
    priority: "high",
    taskType: "DevOps",
    dueDate: "2026-05-20",
    estimatedHours: 16,
    actualHours: 0,
    assigneeIds: ["u_nikolai", "u_kai"],
    clientVisible: false,
    position: 4,
    tags: ["Migration"],
    commentCount: 2,
    attachmentCount: 0,
    subtaskCount: 5,
    subtasksDone: 0,
  },
  // Meridian
  {
    projectId: "p_meridian_app",
    phaseId: "p_meridian_app_phase_5",
    title: "iOS — biometric login + Keychain",
    status: "in_progress",
    priority: "urgent",
    taskType: "Feature",
    dueDate: "2026-05-05",
    estimatedHours: 20,
    actualHours: 14,
    assigneeIds: ["u_nikolai"],
    clientVisible: false,
    position: 1,
    tags: ["iOS", "Auth"],
    commentCount: 7,
    attachmentCount: 0,
    subtaskCount: 4,
    subtasksDone: 3,
  },
  {
    projectId: "p_meridian_app",
    phaseId: "p_meridian_app_phase_5",
    title: "Live market data — websocket layer",
    status: "blocked",
    priority: "urgent",
    taskType: "Feature",
    dueDate: "2026-05-18",
    estimatedHours: 32,
    actualHours: 4,
    assigneeIds: ["u_nikolai"],
    clientVisible: false,
    position: 2,
    tags: ["Realtime"],
    commentCount: 12,
    attachmentCount: 1,
    subtaskCount: 6,
    subtasksDone: 1,
  },
  {
    projectId: "p_meridian_app",
    phaseId: "p_meridian_app_phase_3",
    title: "Portfolio screen — concept exploration",
    status: "in_review",
    priority: "high",
    taskType: "Design",
    dueDate: "2026-04-30",
    estimatedHours: 18,
    actualHours: 16,
    assigneeIds: ["u_lina"],
    reviewerId: "u_avery",
    clientVisible: true,
    position: 3,
    tags: ["UI"],
    figmaUrl: "https://figma.com/file/example2",
    commentCount: 6,
    attachmentCount: 4,
    subtaskCount: 3,
    subtasksDone: 3,
  },
  {
    projectId: "p_meridian_app",
    phaseId: "p_meridian_app_phase_6",
    title: "QA — TestFlight beta cohort 1",
    status: "todo",
    priority: "high",
    taskType: "QA",
    dueDate: "2026-06-10",
    estimatedHours: 24,
    actualHours: 0,
    assigneeIds: ["u_kai"],
    clientVisible: false,
    position: 4,
    tags: ["QA", "Beta"],
    commentCount: 0,
    attachmentCount: 0,
    subtaskCount: 0,
    subtasksDone: 0,
  },
  // Haus of Mode
  {
    projectId: "p_haus_brand",
    phaseId: "p_haus_brand_phase_4",
    title: "Logo system — primary mark exploration",
    status: "in_review",
    priority: "high",
    taskType: "Design",
    dueDate: "2026-04-28",
    estimatedHours: 30,
    actualHours: 28,
    assigneeIds: ["u_lina", "u_avery"],
    reviewerId: "u_avery",
    clientVisible: true,
    position: 1,
    tags: ["Logo"],
    figmaUrl: "https://figma.com/file/example3",
    commentCount: 14,
    attachmentCount: 6,
    subtaskCount: 4,
    subtasksDone: 4,
  },
  {
    projectId: "p_haus_brand",
    phaseId: "p_haus_brand_phase_5",
    title: "Type system pairings",
    status: "in_progress",
    priority: "medium",
    taskType: "Design",
    dueDate: "2026-05-04",
    estimatedHours: 12,
    actualHours: 5,
    assigneeIds: ["u_sade"],
    clientVisible: true,
    position: 2,
    tags: ["Typography"],
    commentCount: 2,
    attachmentCount: 1,
    subtaskCount: 0,
    subtasksDone: 0,
  },
  {
    projectId: "p_haus_brand",
    phaseId: "p_haus_brand_phase_6",
    title: "Brand guidelines document — v1",
    status: "todo",
    priority: "medium",
    taskType: "Content",
    dueDate: "2026-05-14",
    estimatedHours: 16,
    actualHours: 0,
    assigneeIds: ["u_avery"],
    clientVisible: true,
    position: 3,
    tags: ["Guidelines"],
    commentCount: 0,
    attachmentCount: 0,
    subtaskCount: 0,
    subtasksDone: 0,
  },
  // Terra Verde
  {
    projectId: "p_terra_seo",
    phaseId: "p_terra_seo_phase_1",
    title: "Technical SEO audit — April",
    status: "in_progress",
    priority: "medium",
    taskType: "Research",
    dueDate: "2026-05-02",
    estimatedHours: 8,
    actualHours: 4,
    assigneeIds: ["u_marcus"],
    clientVisible: true,
    position: 1,
    tags: ["SEO", "Audit"],
    commentCount: 1,
    attachmentCount: 0,
    subtaskCount: 5,
    subtasksDone: 2,
  },
  {
    projectId: "p_terra_seo",
    phaseId: "p_terra_seo_phase_3",
    title: "Content calendar — May–June",
    status: "todo",
    priority: "low",
    taskType: "Content",
    dueDate: "2026-05-10",
    estimatedHours: 6,
    actualHours: 0,
    assigneeIds: ["u_sade"],
    clientVisible: true,
    position: 2,
    tags: ["Content"],
    commentCount: 0,
    attachmentCount: 0,
    subtaskCount: 0,
    subtasksDone: 0,
  },
];

const SUBTASK_FRAGMENTS = [
  "Spec out requirements",
  "Draft outline + open questions",
  "Implement happy path",
  "Edge cases + error handling",
  "Add unit tests",
  "QA pass",
  "Self-review",
  "PR + reviewer notes",
  "Documentation",
];

export const TASKS: Task[] = taskSeeds.map((t, idx) => {
  const project = PROJECTS.find((p) => p.id === t.projectId)!;
  const subtasks = Array.from({ length: t.subtaskCount }, (_, i) => ({
    id: `t_${idx + 1}_st_${i + 1}`,
    title:
      SUBTASK_FRAGMENTS[(idx + i) % SUBTASK_FRAGMENTS.length] ?? `Step ${i + 1}`,
    done: i < t.subtasksDone,
    position: (i + 1) * 1000,
  }));
  return {
    ...t,
    id: `t_${idx + 1}`,
    code: `${project.code}-T${String(idx + 1).padStart(3, "0")}`,
    organizationId: ORG.id,
    subtasks,
    createdAt: "2026-04-15T09:00:00Z",
    updatedAt: "2026-04-26T17:30:00Z",
  };
});

export const COMMENTS: Comment[] = [
  {
    id: "cm_1",
    taskId: "t_2",
    authorId: "u_marcus",
    body: "Love the depth of field on the reel. Can we explore a slower entry on the headline word-by-word?",
    createdAt: "2026-04-25T10:24:00Z",
  },
  {
    id: "cm_2",
    taskId: "t_2",
    authorId: "u_lina",
    body: "On it — pushing v2 with a cubic-bezier(0.22, 1, 0.36, 1) entry tonight.",
    createdAt: "2026-04-25T11:08:00Z",
  },
  {
    id: "cm_3",
    taskId: "t_4",
    authorId: "u_nikolai",
    body: "Date picker is using react-day-picker. Need product input on whether group bookings should support split-night editing.",
    createdAt: "2026-04-26T09:14:00Z",
  },
];

export const TIME_ENTRIES: TimeEntry[] = [
  {
    id: "te_1",
    taskId: "t_2",
    userId: "u_lina",
    date: "2026-04-26",
    durationMinutes: 195,
    description: "Hero v2 — entry animation polish",
    billable: true,
  },
  {
    id: "te_2",
    taskId: "t_4",
    userId: "u_nikolai",
    date: "2026-04-26",
    durationMinutes: 240,
    description: "Date picker keyboard navigation",
    billable: true,
  },
  {
    id: "te_3",
    taskId: "t_9",
    userId: "u_nikolai",
    date: "2026-04-25",
    durationMinutes: 360,
    description: "Checkout API — Stripe webhook handling",
    billable: true,
  },
];

function buildInvoice(
  partial: Omit<
    Invoice,
    | "id"
    | "organizationId"
    | "subtotal"
    | "taxAmount"
    | "total"
  > & { id: string },
): Invoice {
  const subtotal = partial.lineItems.reduce((s, li) => s + li.amount, 0);
  const taxAmount = subtotal * partial.taxRate;
  const total = subtotal + taxAmount;
  return {
    ...partial,
    organizationId: ORG.id,
    subtotal,
    taxAmount,
    total,
  };
}

export const INVOICES: Invoice[] = [
  buildInvoice({
    id: "inv_1",
    number: "INV-2026-0014",
    projectId: "p_lumiere_site",
    clientId: "c_lumiere",
    type: "milestone",
    status: "paid",
    issueDate: "2026-03-15",
    dueDate: "2026-04-14",
    sentAt: "2026-03-15T10:00:00Z",
    paidAt: "2026-04-02T11:30:00Z",
    currency: "USD",
    notes:
      "Milestone 1: Discovery, Information Architecture, and Wireframing.",
    taxRate: 0.05,
    amountPaid: 38062.5,
    lineItems: [
      {
        id: "li_1",
        description: "Stakeholder discovery + workshops (M1)",
        quantity: 1,
        unit: "milestone",
        rate: 14000,
        amount: 14000,
      },
      {
        id: "li_2",
        description: "Information architecture + sitemap",
        quantity: 1,
        unit: "milestone",
        rate: 9500,
        amount: 9500,
      },
      {
        id: "li_3",
        description: "Wireframes (desktop + mobile)",
        quantity: 1,
        unit: "milestone",
        rate: 12750,
        amount: 12750,
      },
    ],
  }),
  buildInvoice({
    id: "inv_2",
    number: "INV-2026-0023",
    projectId: "p_lumiere_site",
    clientId: "c_lumiere",
    type: "milestone",
    status: "sent",
    issueDate: "2026-04-22",
    dueDate: "2026-05-22",
    sentAt: "2026-04-22T14:00:00Z",
    currency: "USD",
    notes: "Milestone 2: UI design system + key page concepts.",
    taxRate: 0.05,
    amountPaid: 0,
    lineItems: [
      {
        id: "li_4",
        description: "UI design system + token library",
        quantity: 1,
        unit: "milestone",
        rate: 22000,
        amount: 22000,
      },
      {
        id: "li_5",
        description: "Key page concepts (Home, PDP, Booking)",
        quantity: 1,
        unit: "milestone",
        rate: 18500,
        amount: 18500,
      },
    ],
  }),
  buildInvoice({
    id: "inv_3",
    number: "INV-2026-0019",
    projectId: "p_orchid_ecom",
    clientId: "c_orchid",
    type: "milestone",
    status: "overdue",
    issueDate: "2026-03-28",
    dueDate: "2026-04-12",
    sentAt: "2026-03-28T09:30:00Z",
    currency: "USD",
    notes: "Phase 1: Theme architecture and product detail page.",
    taxRate: 0,
    amountPaid: 0,
    lineItems: [
      {
        id: "li_6",
        description: "Shopify theme architecture + setup",
        quantity: 1,
        unit: "milestone",
        rate: 11500,
        amount: 11500,
      },
      {
        id: "li_7",
        description: "PDP design + variant picker animation",
        quantity: 1,
        unit: "milestone",
        rate: 9800,
        amount: 9800,
      },
    ],
  }),
  buildInvoice({
    id: "inv_4",
    number: "INV-2026-0027",
    projectId: "p_meridian_app",
    clientId: "c_meridian",
    type: "time_materials",
    status: "sent",
    issueDate: "2026-04-26",
    dueDate: "2026-05-26",
    sentAt: "2026-04-26T16:00:00Z",
    currency: "USD",
    notes: "March time & materials billing.",
    taxRate: 0.05,
    amountPaid: 0,
    lineItems: [
      {
        id: "li_8",
        description: "Senior iOS engineering (Nikolai)",
        quantity: 142,
        unit: "hours",
        rate: 185,
        amount: 26270,
      },
      {
        id: "li_9",
        description: "Lead UX design (Lina)",
        quantity: 88,
        unit: "hours",
        rate: 165,
        amount: 14520,
      },
      {
        id: "li_10",
        description: "Project management (Marcus)",
        quantity: 36,
        unit: "hours",
        rate: 145,
        amount: 5220,
      },
    ],
  }),
  buildInvoice({
    id: "inv_5",
    number: "INV-2026-0030",
    projectId: "p_terra_seo",
    clientId: "c_terra",
    type: "retainer",
    status: "draft",
    issueDate: "2026-05-01",
    dueDate: "2026-05-15",
    currency: "USD",
    notes: "Q2 SEO retainer — May.",
    taxRate: 0,
    amountPaid: 0,
    lineItems: [
      {
        id: "li_11",
        description: "Monthly SEO retainer — May",
        quantity: 1,
        unit: "month",
        rate: 6000,
        amount: 6000,
      },
    ],
  }),
  buildInvoice({
    id: "inv_6",
    number: "INV-2026-0017",
    projectId: "p_haus_brand",
    clientId: "c_haus",
    type: "fixed_installment",
    status: "paid",
    issueDate: "2026-03-25",
    dueDate: "2026-04-25",
    sentAt: "2026-03-25T11:00:00Z",
    paidAt: "2026-04-19T15:30:00Z",
    currency: "EUR",
    notes: "50% upfront installment for SS27 brand identity.",
    taxRate: 0.19,
    amountPaid: 34510,
    lineItems: [
      {
        id: "li_12",
        description: "SS27 brand identity — 50% installment",
        quantity: 1,
        unit: "fixed",
        rate: 29000,
        amount: 29000,
      },
    ],
  }),
];

export const AUTOMATIONS: AutomationRule[] = [
  {
    id: "auto_1",
    organizationId: ORG.id,
    name: "Notify PM when task moves to Done",
    description:
      "When any task is marked Done, notify the project manager and update phase progress.",
    isActive: true,
    category: "status",
    trigger: {
      id: "trg_1",
      type: "task_status_change",
      label: "Task moves to Done",
      description: "Any task status changes to Done",
      meta: { from: "any", to: "done" },
    },
    conditions: [],
    actions: [
      {
        id: "act_1",
        type: "send_notification",
        label: "Notify project manager",
        description: "In-app notification to the project's PM",
      },
      {
        id: "act_2",
        type: "update_priority",
        label: "Recalculate phase progress",
        description: "Update parent phase completion %",
      },
    ],
    runCount: 482,
    lastRunAt: "2026-04-28T16:14:00Z",
    createdAt: "2026-01-12T10:00:00Z",
  },
  {
    id: "auto_2",
    organizationId: ORG.id,
    name: "Auto-assign design tasks to Lina",
    description:
      "New tasks tagged Design or with type=Design auto-route to the design lead.",
    isActive: true,
    category: "assignment",
    trigger: {
      id: "trg_2",
      type: "task_created",
      label: "New task created",
      description: "Whenever a task is added to any project",
    },
    conditions: [
      {
        id: "cnd_1",
        type: "task_created",
        label: "Task type is Design",
        description: "task.type = Design or tags include Design",
      },
    ],
    actions: [
      {
        id: "act_3",
        type: "assign_user",
        label: "Assign to Lina Okafor",
        description: "Add as task assignee",
        meta: { userId: "u_lina" },
      },
      {
        id: "act_4",
        type: "post_slack",
        label: "Post to #design",
        description: "Slack channel notification",
      },
    ],
    runCount: 64,
    lastRunAt: "2026-04-27T11:42:00Z",
    createdAt: "2026-02-04T14:20:00Z",
  },
  {
    id: "auto_3",
    organizationId: ORG.id,
    name: "Alert PM at 80% budget burn",
    description:
      "When project actual cost exceeds 80% of budget, raise a yellow flag.",
    isActive: true,
    category: "budget",
    trigger: {
      id: "trg_3",
      type: "budget_threshold",
      label: "Project burn ≥ 80%",
      description: "Recomputed when time is logged",
    },
    conditions: [
      {
        id: "cnd_2",
        type: "budget_threshold",
        label: "Project status is Active",
        description: "Skip on hold or completed projects",
      },
    ],
    actions: [
      {
        id: "act_5",
        type: "send_notification",
        label: "Alert PM + Account Manager",
        description: "In-app + email digest",
      },
      {
        id: "act_6",
        type: "update_priority",
        label: "Set project health to Yellow",
        description: "Auto-update health indicator",
      },
    ],
    runCount: 7,
    lastRunAt: "2026-04-26T09:08:00Z",
    createdAt: "2026-01-18T09:30:00Z",
  },
  {
    id: "auto_4",
    organizationId: ORG.id,
    name: "Three-day deadline reminder",
    description:
      "Email assignees three days before any task's due date if not yet done.",
    isActive: true,
    category: "deadline",
    trigger: {
      id: "trg_4",
      type: "schedule_recurring",
      label: "Daily at 9:00 AM",
      description: "Cron-style daily evaluation",
    },
    conditions: [
      {
        id: "cnd_3",
        type: "task_overdue",
        label: "Due in exactly 3 days",
        description: "task.dueDate = today + 3",
      },
      {
        id: "cnd_4",
        type: "task_overdue",
        label: "Status not Done",
        description: "task.status != done",
      },
    ],
    actions: [
      {
        id: "act_7",
        type: "send_email",
        label: "Email all assignees",
        description: "Reminder with deep link to task",
      },
    ],
    runCount: 218,
    lastRunAt: "2026-04-29T09:00:00Z",
    createdAt: "2026-01-22T08:00:00Z",
  },
  {
    id: "auto_5",
    organizationId: ORG.id,
    name: "Generate invoice on milestone approval",
    description:
      "When a client approves a milestone, auto-draft the corresponding invoice for PM review.",
    isActive: true,
    category: "approval",
    trigger: {
      id: "trg_5",
      type: "approval_received",
      label: "Milestone approved by client",
      description: "Approval event fires from portal",
    },
    conditions: [],
    actions: [
      {
        id: "act_8",
        type: "create_invoice",
        label: "Draft milestone invoice",
        description: "Auto-populate line items from milestone scope",
      },
      {
        id: "act_9",
        type: "send_notification",
        label: "Notify finance + PM",
        description: "In-app notification with invoice link",
      },
    ],
    runCount: 12,
    lastRunAt: "2026-04-22T14:00:00Z",
    createdAt: "2026-02-14T10:15:00Z",
  },
  {
    id: "auto_6",
    organizationId: ORG.id,
    name: "Monthly retainer task generation",
    description:
      "On the 1st of each month, create the recurring task set for active retainer projects from a template.",
    isActive: false,
    category: "recurring",
    trigger: {
      id: "trg_6",
      type: "schedule_recurring",
      label: "1st of month, 6:00 AM",
      description: "Cron monthly",
    },
    conditions: [
      {
        id: "cnd_5",
        type: "schedule_recurring",
        label: "Project is retainer + active",
        description: "billingModel=retainer, status=active",
      },
    ],
    actions: [
      {
        id: "act_10",
        type: "create_task",
        label: "Create monthly task set",
        description: "From project template",
      },
    ],
    runCount: 4,
    lastRunAt: "2026-04-01T06:00:00Z",
    createdAt: "2026-01-30T15:00:00Z",
  },
];

export const FILES: ProjectFile[] = [
  {
    id: "f_1",
    projectId: "p_lumiere_site",
    fileName: "Hero_v2_export.mp4",
    sizeBytes: 18_400_000,
    mimeType: "video/mp4",
    version: 2,
    uploadedBy: "u_lina",
    clientVisible: true,
    createdAt: "2026-04-25T14:00:00Z",
  },
  {
    id: "f_2",
    projectId: "p_haus_brand",
    fileName: "Logo_exploration_v3.pdf",
    sizeBytes: 6_200_000,
    mimeType: "application/pdf",
    version: 3,
    uploadedBy: "u_lina",
    clientVisible: true,
    createdAt: "2026-04-24T11:00:00Z",
  },
];

// ----------------------------------------------------------------------------
// Quotes / estimates
// ----------------------------------------------------------------------------
function buildQuoteVersion(
  id: string,
  versionNumber: number,
  status: QuoteVersion["status"],
  lines: Omit<QuoteLineItem, "amount">[],
  taxRate: number,
  createdAt: string,
  notes?: string,
  sentAt?: string,
): QuoteVersion {
  const lineItems: QuoteLineItem[] = lines.map((l) => ({
    ...l,
    amount: l.quantity * l.rate,
  }));
  const subtotal = lineItems.reduce((s, l) => s + l.amount, 0);
  const internalCost = lineItems.reduce(
    (s, l) => s + l.quantity * l.costRate,
    0,
  );
  const taxAmount = subtotal * taxRate;
  return {
    id,
    versionNumber,
    status,
    lineItems,
    notes,
    subtotal,
    internalCost,
    taxRate,
    taxAmount,
    total: subtotal + taxAmount,
    createdAt,
    sentAt,
  };
}

export const QUOTES: Quote[] = [
  {
    id: "q_1",
    organizationId: ORG.id,
    number: "Q-2026-0008",
    clientId: "c_lumiere",
    name: "Lumière flagship website — full rebuild",
    type: "web_dev",
    description:
      "Editorial-grade redesign with bilingual EN/FR support and a custom booking experience.",
    status: "converted",
    currency: "USD",
    validUntil: "2026-03-15",
    currentVersionId: "qv_1_2",
    convertedToProjectId: "p_lumiere_site",
    createdBy: "u_avery",
    createdAt: "2026-02-12T10:00:00Z",
    versions: [
      buildQuoteVersion(
        "qv_1_1",
        1,
        "superseded",
        [
          {
            id: "qli_1_1_1",
            category: "Discovery & IA",
            description: "Stakeholder workshops, sitemap, content audit",
            quantity: 1,
            unit: "milestone",
            rate: 28000,
            costRate: 17500,
          },
          {
            id: "qli_1_1_2",
            category: "Design",
            description: "UI design system + 8 key page templates",
            quantity: 1,
            unit: "milestone",
            rate: 52000,
            costRate: 30000,
          },
          {
            id: "qli_1_1_3",
            category: "Development",
            description: "Frontend, backend, booking integration",
            quantity: 1,
            unit: "milestone",
            rate: 78000,
            costRate: 48000,
          },
        ],
        0.05,
        "2026-02-12T10:00:00Z",
        "Initial scope. Replaced after content scope expanded.",
        "2026-02-12T15:00:00Z",
      ),
      buildQuoteVersion(
        "qv_1_2",
        2,
        "accepted",
        [
          {
            id: "qli_1_2_1",
            category: "Discovery & IA",
            description: "Stakeholder workshops, sitemap, content audit",
            quantity: 1,
            unit: "milestone",
            rate: 28000,
            costRate: 17500,
          },
          {
            id: "qli_1_2_2",
            category: "Design",
            description: "UI design system + 12 page templates (FR included)",
            quantity: 1,
            unit: "milestone",
            rate: 64000,
            costRate: 36000,
          },
          {
            id: "qli_1_2_3",
            category: "Development",
            description:
              "Frontend, backend, Synxis booking integration, bilingual setup",
            quantity: 1,
            unit: "milestone",
            rate: 88000,
            costRate: 54000,
          },
          {
            id: "qli_1_2_4",
            category: "Launch & QA",
            description: "QA, staging review, content migration, launch",
            quantity: 1,
            unit: "milestone",
            rate: 16500,
            costRate: 9500,
          },
        ],
        0.05,
        "2026-02-18T11:30:00Z",
        "Includes bilingual content, Synxis booking, 4 milestone payments.",
        "2026-02-18T15:30:00Z",
      ),
    ],
  },
  {
    id: "q_2",
    organizationId: ORG.id,
    number: "Q-2026-0014",
    clientId: "c_orchid",
    name: "Orchid & Vine — Shopify Plus replatform",
    type: "web_dev",
    description: "Headless cart, custom theme, migration from BigCommerce.",
    status: "accepted",
    currency: "USD",
    validUntil: "2026-04-30",
    currentVersionId: "qv_2_1",
    createdBy: "u_avery",
    createdAt: "2026-03-22T14:00:00Z",
    versions: [
      buildQuoteVersion(
        "qv_2_1",
        1,
        "accepted",
        [
          {
            id: "qli_2_1_1",
            category: "Strategy",
            description: "Tech audit + Shopify Plus setup",
            quantity: 1,
            unit: "milestone",
            rate: 14500,
            costRate: 8500,
          },
          {
            id: "qli_2_1_2",
            category: "Design",
            description: "Custom theme + PDP variant picker animation",
            quantity: 1,
            unit: "milestone",
            rate: 32000,
            costRate: 19000,
          },
          {
            id: "qli_2_1_3",
            category: "Development",
            description: "Headless cart + checkout API, theme build",
            quantity: 1,
            unit: "milestone",
            rate: 38000,
            costRate: 24000,
          },
          {
            id: "qli_2_1_4",
            category: "Migration",
            description: "Orders + customer migration, launch support",
            quantity: 1,
            unit: "milestone",
            rate: 11500,
            costRate: 7000,
          },
        ],
        0.05,
        "2026-03-22T14:00:00Z",
        "Net 30 milestone billing.",
        "2026-03-23T10:00:00Z",
      ),
    ],
  },
  {
    id: "q_3",
    organizationId: ORG.id,
    number: "Q-2026-0019",
    clientId: "c_haus",
    name: "Haus of Mode — SS27 brand identity refresh",
    type: "branding",
    description:
      "Logo system, type, color, motion guidelines for the SS27 collection.",
    status: "sent",
    currency: "EUR",
    validUntil: "2026-05-15",
    currentVersionId: "qv_3_1",
    createdBy: "u_avery",
    createdAt: "2026-04-08T09:30:00Z",
    versions: [
      buildQuoteVersion(
        "qv_3_1",
        1,
        "sent",
        [
          {
            id: "qli_3_1_1",
            category: "Discovery",
            description: "Brand audit + research moodboards",
            quantity: 1,
            unit: "milestone",
            rate: 6500,
            costRate: 3800,
          },
          {
            id: "qli_3_1_2",
            category: "Identity",
            description: "Logo system + primary mark + monogram",
            quantity: 1,
            unit: "milestone",
            rate: 18500,
            costRate: 11500,
          },
          {
            id: "qli_3_1_3",
            category: "System",
            description: "Type pairings + color palette + motion principles",
            quantity: 1,
            unit: "milestone",
            rate: 14000,
            costRate: 8500,
          },
          {
            id: "qli_3_1_4",
            category: "Delivery",
            description: "Brand guidelines PDF + asset package",
            quantity: 1,
            unit: "milestone",
            rate: 19000,
            costRate: 10500,
          },
        ],
        0.19,
        "2026-04-08T09:30:00Z",
        "Includes 19% VAT. Final delivery within 8 weeks of signature.",
        "2026-04-08T16:00:00Z",
      ),
    ],
  },
  {
    id: "q_4",
    organizationId: ORG.id,
    number: "Q-2026-0023",
    clientId: "c_meridian",
    name: "Meridian — Q3 mobile feature build (T&M)",
    type: "app_dev",
    description: "Time & materials estimate for Q3 feature roadmap.",
    status: "draft",
    currency: "USD",
    validUntil: "2026-06-30",
    currentVersionId: "qv_4_1",
    createdBy: "u_marcus",
    createdAt: "2026-04-25T11:00:00Z",
    versions: [
      buildQuoteVersion(
        "qv_4_1",
        1,
        "draft",
        [
          {
            id: "qli_4_1_1",
            category: "iOS engineering",
            description: "Senior iOS engineer · estimated allocation",
            quantity: 320,
            unit: "hours",
            rate: 185,
            costRate: 110,
          },
          {
            id: "qli_4_1_2",
            category: "Design",
            description: "Lead UX design",
            quantity: 180,
            unit: "hours",
            rate: 165,
            costRate: 95,
          },
          {
            id: "qli_4_1_3",
            category: "Project management",
            description: "PM oversight",
            quantity: 80,
            unit: "hours",
            rate: 145,
            costRate: 85,
          },
        ],
        0.05,
        "2026-04-25T11:00:00Z",
        "Indicative — actuals billed monthly with rate card on file.",
      ),
    ],
  },
];

// ----------------------------------------------------------------------------
// Timesheet submissions
// ----------------------------------------------------------------------------
export const TIMESHEET_SUBMISSIONS: TimesheetSubmission[] = [
  {
    id: "ts_1",
    organizationId: ORG.id,
    userId: "u_lina",
    weekStart: "2026-04-19",
    status: "approved",
    totalMinutes: 38 * 60,
    billableMinutes: 36 * 60,
    entryIds: [],
    submittedAt: "2026-04-25T17:30:00Z",
    reviewedAt: "2026-04-26T10:00:00Z",
    reviewedBy: "u_marcus",
    notes: "Quiet week, focused on Lumière hero animation polish.",
  },
  {
    id: "ts_2",
    organizationId: ORG.id,
    userId: "u_nikolai",
    weekStart: "2026-04-19",
    status: "approved",
    totalMinutes: 42 * 60,
    billableMinutes: 41 * 60,
    entryIds: [],
    submittedAt: "2026-04-25T19:14:00Z",
    reviewedAt: "2026-04-26T10:02:00Z",
    reviewedBy: "u_marcus",
  },
  {
    id: "ts_3",
    organizationId: ORG.id,
    userId: "u_lina",
    weekStart: "2026-04-26",
    status: "submitted",
    totalMinutes: 35 * 60,
    billableMinutes: 33 * 60,
    entryIds: [],
    submittedAt: "2026-04-29T08:00:00Z",
    notes: "Hero v2 + variant picker animations + Logo system finalisation.",
  },
  {
    id: "ts_4",
    organizationId: ORG.id,
    userId: "u_nikolai",
    weekStart: "2026-04-26",
    status: "submitted",
    totalMinutes: 44 * 60,
    billableMinutes: 42 * 60,
    entryIds: [],
    submittedAt: "2026-04-29T07:45:00Z",
    notes: "Booking flow date picker. Long Friday on biometric login.",
  },
  {
    id: "ts_5",
    organizationId: ORG.id,
    userId: "u_sade",
    weekStart: "2026-04-26",
    status: "draft",
    totalMinutes: 18 * 60,
    billableMinutes: 16 * 60,
    entryIds: [],
  },
];

// ----------------------------------------------------------------------------
// User skills
// ----------------------------------------------------------------------------
export const SKILLS: string[] = [
  "Figma",
  "Brand identity",
  "UX research",
  "React",
  "Next.js",
  "TypeScript",
  "Node.js",
  "iOS / Swift",
  "React Native",
  "PostgreSQL",
  "DevOps",
  "Copywriting",
  "SEO",
  "Google Ads",
  "Project management",
  "QA / Testing",
];

export const USER_SKILLS: UserSkill[] = [
  // Avery — leadership, design oversight
  { userId: "u_avery", skill: "Figma", proficiency: 4 },
  { userId: "u_avery", skill: "Brand identity", proficiency: 4 },
  { userId: "u_avery", skill: "UX research", proficiency: 3 },
  { userId: "u_avery", skill: "Project management", proficiency: 3 },
  // Marcus — PM
  { userId: "u_marcus", skill: "Project management", proficiency: 4 },
  { userId: "u_marcus", skill: "SEO", proficiency: 2 },
  { userId: "u_marcus", skill: "Copywriting", proficiency: 2 },
  { userId: "u_marcus", skill: "UX research", proficiency: 3 },
  // Lina — design
  { userId: "u_lina", skill: "Figma", proficiency: 4 },
  { userId: "u_lina", skill: "Brand identity", proficiency: 4 },
  { userId: "u_lina", skill: "UX research", proficiency: 3 },
  // Nikolai — engineering
  { userId: "u_nikolai", skill: "React", proficiency: 4 },
  { userId: "u_nikolai", skill: "Next.js", proficiency: 4 },
  { userId: "u_nikolai", skill: "TypeScript", proficiency: 4 },
  { userId: "u_nikolai", skill: "Node.js", proficiency: 4 },
  { userId: "u_nikolai", skill: "iOS / Swift", proficiency: 3 },
  { userId: "u_nikolai", skill: "React Native", proficiency: 3 },
  { userId: "u_nikolai", skill: "PostgreSQL", proficiency: 3 },
  { userId: "u_nikolai", skill: "DevOps", proficiency: 2 },
  // Sade — content + design
  { userId: "u_sade", skill: "Copywriting", proficiency: 4 },
  { userId: "u_sade", skill: "Figma", proficiency: 3 },
  { userId: "u_sade", skill: "SEO", proficiency: 3 },
  // Kai — QA
  { userId: "u_kai", skill: "QA / Testing", proficiency: 4 },
  { userId: "u_kai", skill: "DevOps", proficiency: 2 },
];

// ----------------------------------------------------------------------------
// Multi-currency FX (PRD §5.6.3)
// ----------------------------------------------------------------------------
export const BASE_CURRENCY = "USD";

export const FX_RATES: FxRate[] = [
  { currency: "EUR", rateToBase: 1.08, updatedAt: "2026-04-29T00:00:00Z" },
  { currency: "GBP", rateToBase: 1.27, updatedAt: "2026-04-29T00:00:00Z" },
  { currency: "AED", rateToBase: 0.272, updatedAt: "2026-04-29T00:00:00Z" },
];

// ----------------------------------------------------------------------------
// Budget change requests (PRD §5.5.2)
// ----------------------------------------------------------------------------
export const BUDGET_CHANGES: BudgetChangeRequest[] = [
  {
    id: "bcr_1",
    organizationId: ORG.id,
    projectId: "p_orchid_ecom",
    requestedBy: "u_avery",
    delta: 14000,
    reason:
      "Client added the Klaviyo integration mid-flight; needs an extra phase of dev + QA.",
    status: "pending",
    createdAt: "2026-04-26T10:00:00Z",
  },
  {
    id: "bcr_2",
    organizationId: ORG.id,
    projectId: "p_meridian_app",
    requestedBy: "u_marcus",
    delta: 26000,
    reason:
      "Live market data scope expanded to include 3 new providers and websocket fallback.",
    status: "approved",
    createdAt: "2026-04-15T11:30:00Z",
    reviewedAt: "2026-04-17T15:00:00Z",
    reviewedBy: "u_avery",
    reviewNote: "Approved on the basis of the Q3 roadmap discussion.",
  },
  {
    id: "bcr_3",
    organizationId: ORG.id,
    projectId: "p_lumiere_site",
    requestedBy: "u_marcus",
    delta: -8500,
    reason:
      "Bilingual setup work came in 25% under estimate; offering a partial credit.",
    status: "rejected",
    createdAt: "2026-04-08T09:00:00Z",
    reviewedAt: "2026-04-10T11:00:00Z",
    reviewedBy: "u_avery",
    reviewNote: "Hold credit until next milestone for goodwill on a future quote.",
  },
];

// ----------------------------------------------------------------------------
// Time tracking config (PRD §5.3.2)
// ----------------------------------------------------------------------------
export const TIME_TRACKING_CONFIG: TimeTrackingConfig = {
  rounding: "15min",
  lockedWeeks: ["2026-03-29", "2026-04-05"],
  idleThresholdMinutes: 240,
};
