"use client";

import { useState } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import {
  Bell,
  CheckCircle2,
  AlertTriangle,
  AtSign,
  Clock,
  Receipt,
  Eye,
  X,
  Check,
} from "lucide-react";
import { toast } from "sonner";
import { format, parseISO } from "date-fns";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { useStore } from "@/lib/db/store";
import { cn } from "@/lib/utils";

type NotificationType =
  | "mention"
  | "approval"
  | "deadline"
  | "budget"
  | "invoice"
  | "review";

interface Notification {
  id: string;
  type: NotificationType;
  title: string;
  body: string;
  href: string;
  createdAt: string;
  read: boolean;
  // If set, the notification can be acted on inline without leaving the dropdown.
  inlineAction?: {
    primaryLabel: string;
    secondaryLabel: string;
  };
}

const ICON_MAP: Record<
  NotificationType,
  { icon: React.ComponentType<{ className?: string }>; cls: string }
> = {
  mention: { icon: AtSign, cls: "bg-status-progress/15 text-status-progress" },
  approval: {
    icon: CheckCircle2,
    cls: "bg-status-done/15 text-status-done",
  },
  deadline: {
    icon: Clock,
    cls: "bg-status-revisions/15 text-status-revisions",
  },
  budget: {
    icon: AlertTriangle,
    cls: "bg-status-blocked/15 text-status-blocked",
  },
  invoice: { icon: Receipt, cls: "bg-primary/15 text-primary" },
  review: { icon: Eye, cls: "bg-status-review/15 text-status-review" },
};

// Synthetic notifications derived from the store. In a real backend
// these would be generated by the activity log + automation engine.
function buildNotifications(orgSlug: string): Notification[] {
  return [
    {
      id: "n_1",
      type: "review",
      title: "Design ready for review",
      body: "Editorial homepage hero — concept A is awaiting your review.",
      href: `/${orgSlug}/projects/p_lumiere_site/kanban?task=t_2`,
      createdAt: "2026-04-29T08:42:00Z",
      read: false,
      inlineAction: {
        primaryLabel: "Approve",
        secondaryLabel: "Request changes",
      },
    },
    {
      id: "n_2",
      type: "mention",
      title: "Marcus mentioned you",
      body: "On the Lumière booking flow: \"Need product input on group bookings…\"",
      href: `/${orgSlug}/projects/p_lumiere_site/kanban?task=t_4`,
      createdAt: "2026-04-29T08:14:00Z",
      read: false,
    },
    {
      id: "n_3",
      type: "approval",
      title: "Client approved milestone",
      body: "Lumière approved Milestone 1. Invoice INV-2026-0014 was auto-drafted.",
      href: `/${orgSlug}/invoices/inv_1`,
      createdAt: "2026-04-28T17:30:00Z",
      read: false,
      inlineAction: {
        primaryLabel: "Send invoice",
        secondaryLabel: "Review",
      },
    },
    {
      id: "n_4",
      type: "budget",
      title: "Meridian app at 84% budget",
      body: "Project burn crossed your 80% threshold. Project health flipped to Yellow.",
      href: `/${orgSlug}/projects/p_meridian_app/kanban`,
      createdAt: "2026-04-28T14:08:00Z",
      read: true,
    },
    {
      id: "n_5",
      type: "deadline",
      title: "Task due tomorrow",
      body: "PDP — variant picker animation is due May 2.",
      href: `/${orgSlug}/projects/p_orchid_ecom/kanban?task=t_8`,
      createdAt: "2026-04-28T09:00:00Z",
      read: true,
    },
    {
      id: "n_6",
      type: "invoice",
      title: "Invoice marked paid",
      body: "INV-2026-0014 was paid by Lumière Hotels. $40k cleared.",
      href: `/${orgSlug}/invoices/inv_1`,
      createdAt: "2026-04-27T11:20:00Z",
      read: true,
    },
  ];
}

export function NotificationCenter() {
  const orgSlug = useStore((s) => s.organization.slug);
  const [items, setItems] = useState(() => buildNotifications(orgSlug));
  const [open, setOpen] = useState(false);

  const unread = items.filter((n) => !n.read).length;

  const markAllRead = () => {
    setItems((arr) => arr.map((n) => ({ ...n, read: true })));
  };

  const markRead = (id: string) => {
    setItems((arr) =>
      arr.map((n) => (n.id === id ? { ...n, read: true } : n)),
    );
  };

  const dismissAfterAction = (id: string, message: string) => {
    setItems((arr) => arr.filter((n) => n.id !== id));
    toast.success(message);
  };

  const handlePrimary = (n: Notification) => (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (n.type === "review")
      dismissAfterAction(n.id, "Approved · team has been notified");
    else if (n.type === "approval")
      dismissAfterAction(n.id, "Invoice queued for sending");
    else dismissAfterAction(n.id, "Done");
  };

  const handleSecondary = (n: Notification) => (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (n.type === "review")
      dismissAfterAction(n.id, "Changes requested");
    else dismissAfterAction(n.id, "Snoozed");
  };

  return (
    <DropdownMenu open={open} onOpenChange={setOpen}>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="icon" aria-label="Notifications" className="relative">
          <Bell className="size-4" />
          <AnimatePresence>
            {unread > 0 ? (
              <motion.span
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                exit={{ scale: 0 }}
                className="absolute right-1.5 top-1.5 grid size-4 place-items-center rounded-full bg-status-blocked text-[9px] font-semibold text-white ring-2 ring-background"
              >
                {unread}
              </motion.span>
            ) : null}
          </AnimatePresence>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-[380px] p-0">
        <div className="flex items-center justify-between border-b px-4 py-3">
          <div>
            <p className="text-sm font-semibold">Notifications</p>
            <p className="text-[11px] text-muted-foreground">
              {unread > 0
                ? `${unread} unread`
                : "You're all caught up"}
            </p>
          </div>
          {unread > 0 ? (
            <button
              onClick={markAllRead}
              className="text-xs text-primary hover:underline"
            >
              Mark all read
            </button>
          ) : null}
        </div>

        <div className="max-h-[420px] overflow-y-auto scrollbar-thin">
          {items.length === 0 ? (
            <div className="grid place-items-center py-12 text-center">
              <CheckCircle2 className="mb-2 size-8 text-status-done" />
              <p className="text-sm font-medium">All caught up</p>
              <p className="mt-0.5 text-xs text-muted-foreground">
                No new notifications.
              </p>
            </div>
          ) : (
            <AnimatePresence initial={false}>
              {items.map((n, i) => {
                const meta = ICON_MAP[n.type];
                return (
                  <motion.div
                    key={n.id}
                    layout
                    initial={{ opacity: 0, y: 4 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{
                      opacity: 0,
                      x: 30,
                      height: 0,
                      transition: { duration: 0.25 },
                    }}
                    transition={{ delay: i * 0.02 }}
                    className={cn(
                      "border-b transition-colors",
                      !n.read && "bg-primary/5",
                    )}
                  >
                    <Link
                      href={n.href}
                      onClick={() => {
                        markRead(n.id);
                        setOpen(false);
                      }}
                      className="flex gap-3 px-4 py-3 transition-colors hover:bg-accent"
                    >
                      <div
                        className={cn(
                          "grid size-8 shrink-0 place-items-center rounded-md",
                          meta.cls,
                        )}
                      >
                        <meta.icon className="size-4" />
                      </div>
                      <div className="min-w-0 flex-1">
                        <div className="flex items-start justify-between gap-2">
                          <p className="text-sm font-medium leading-tight">
                            {n.title}
                          </p>
                          {!n.read ? (
                            <span className="mt-1 size-1.5 shrink-0 rounded-full bg-primary" />
                          ) : null}
                        </div>
                        <p className="mt-0.5 line-clamp-2 text-xs text-muted-foreground leading-snug">
                          {n.body}
                        </p>
                        <p className="mt-1 text-[10px] text-muted-foreground">
                          {format(parseISO(n.createdAt), "MMM d · h:mm a")}
                        </p>
                      </div>
                    </Link>
                    {n.inlineAction ? (
                      <div className="flex items-center gap-1.5 px-4 pb-3">
                        <Button
                          size="sm"
                          className="h-7 px-2 text-[11px]"
                          onClick={handlePrimary(n)}
                        >
                          <Check className="size-3" />
                          {n.inlineAction.primaryLabel}
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          className="h-7 px-2 text-[11px]"
                          onClick={handleSecondary(n)}
                        >
                          <X className="size-3" />
                          {n.inlineAction.secondaryLabel}
                        </Button>
                      </div>
                    ) : null}
                  </motion.div>
                );
              })}
            </AnimatePresence>
          )}
        </div>

        <div className="border-t px-4 py-2">
          <Link
            href={`/${orgSlug}/dashboard`}
            onClick={() => setOpen(false)}
            className="block rounded-md py-1.5 text-center text-xs font-medium text-primary hover:bg-primary/5"
          >
            View all activity
          </Link>
        </div>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
